

server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: merchant
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/merchant/**
        - id: order
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/order/**
